# -*- encoding: utf-8 -*-

=begin
#DPO-DCSATrackAndTrace-API-V2

#Provides equipment actual milestones along with Estimated Time of Arrival following DCSA standards

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

$:.push File.expand_path("../lib", __FILE__)
require "msc_client/version"

Gem::Specification.new do |s|
  s.name        = "msc_client"
  s.version     = MSCClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = [""]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "DPO-DCSATrackAndTrace-API-V2 Ruby Gem"
  s.description = "Provides equipment actual milestones along with Estimated Time of Arrival following DCSA standards"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.7"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
