=begin
#DPO-DCSATrackAndTrace-API-V2

#Provides equipment actual milestones along with Estimated Time of Arrival following DCSA standards

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for MSCClient::EventsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EventsApi' do
  before do
    # run before each test
    @api_instance = MSCClient::EventsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EventsApi' do
    it 'should create an instance of EventsApi' do
      expect(@api_instance).to be_instance_of(MSCClient::EventsApi)
    end
  end

  # unit tests for get_events
  # Find events by Carrier BookingReference, Transport DocumentReference (Bill of lading) or Equipment Reference.The endpoint **requires** only 1 of the 3 query parameters to be used
  # @param [Hash] opts the optional parameters
  # @option opts [String] :carrier_booking_reference A set of unique characters provided by carrier to identify a booking.  Specifying this filter will only return events related to this particular carrierBookingReference
  # @option opts [String] :transport_document_reference A unique number reference allocated by the shipping line to the transport document and   the main number used for the tracking of the status of the shipment.  Specifying this filter will only return events related to this particular transportDocumentReference
  # @option opts [String] :equipment_reference Will filter by the unique identifier for the equipment, which should follow the BIC ISO Container Identification Number where possible.  Specifying this filter will only return events related to this particular equipmentReference
  # @return [Array<Event>]
  describe 'get_events test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
