=begin
#DPO-DCSATrackAndTrace-API-V2

#Provides equipment actual milestones along with Estimated Time of Arrival following DCSA standards

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

# Common files
require 'msc_client/api_client'
require 'msc_client/api_error'
require 'msc_client/version'
require 'msc_client/configuration'

# Models
require 'msc_client/models/document_reference'
require 'msc_client/models/equipment_event'
require 'msc_client/models/error'
require 'msc_client/models/errors'
require 'msc_client/models/event'
require 'msc_client/models/event_location'
require 'msc_client/models/events'
require 'msc_client/models/shipment_event'
require 'msc_client/models/transport_call'
require 'msc_client/models/transport_event'
require 'msc_client/models/vessel'

# APIs
require 'msc_client/api/events_api'

module MSCClient
  class << self
    # Customize default settings for the SDK using block.
    #   MSCClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
