=begin
#DPO-DCSATrackAndTrace-API-V2

#Provides equipment actual milestones along with Estimated Time of Arrival following DCSA standards

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'date'
require 'time'

module MSCClient
  # The transport event entity is a specialization of the event entity to support specification of data that only applies to a transport event
  class TransportCall
    # The unique identifier for a transport call (PK)
    attr_accessor :transport_call_id

    # The code of the service for which the schedule details are published.  The vessel operator-specific identifier of the Voyage.  In case there are multiple voyages the export voyage is chosen
    attr_accessor :carrier_service_code

    # The vessel operator-specific identifier of the export Voyage
    attr_accessor :export_voyage_number

    # The vessel operator-specific identifier of the import Voyage
    attr_accessor :import_voyage_number

    # Transport operator's key that uniquely identifies each individual call.   This key is essential to distinguish between two separate calls at the same location within one voyage
    attr_accessor :un_location_code

    # The code used for identifying the specific facility
    attr_accessor :facility_code

    # The provider used for identifying the facility Code. List of Values: SMDG, BIC
    attr_accessor :facility_code_list_provider

    # The code to identify the specific type of facility
    attr_accessor :facility_type_code

    # An alternative way to capture the facility when no standardized DCSA facility code can be found
    attr_accessor :other_facility

    # A code specifying a type of transport mode
    attr_accessor :mode_of_transport

    attr_accessor :vessel

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'transport_call_id' => :'transportCallID',
        :'carrier_service_code' => :'carrierServiceCode',
        :'export_voyage_number' => :'exportVoyageNumber',
        :'import_voyage_number' => :'importVoyageNumber',
        :'un_location_code' => :'unLocationCode',
        :'facility_code' => :'facilityCode',
        :'facility_code_list_provider' => :'facilityCodeListProvider',
        :'facility_type_code' => :'facilityTypeCode',
        :'other_facility' => :'otherFacility',
        :'mode_of_transport' => :'modeOfTransport',
        :'vessel' => :'vessel'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'transport_call_id' => :'String',
        :'carrier_service_code' => :'String',
        :'export_voyage_number' => :'String',
        :'import_voyage_number' => :'String',
        :'un_location_code' => :'String',
        :'facility_code' => :'String',
        :'facility_code_list_provider' => :'String',
        :'facility_type_code' => :'String',
        :'other_facility' => :'String',
        :'mode_of_transport' => :'String',
        :'vessel' => :'Vessel'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MSCClient::TransportCall` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MSCClient::TransportCall`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'transport_call_id')
        self.transport_call_id = attributes[:'transport_call_id']
      else
        self.transport_call_id = nil
      end

      if attributes.key?(:'carrier_service_code')
        self.carrier_service_code = attributes[:'carrier_service_code']
      end

      if attributes.key?(:'export_voyage_number')
        self.export_voyage_number = attributes[:'export_voyage_number']
      end

      if attributes.key?(:'import_voyage_number')
        self.import_voyage_number = attributes[:'import_voyage_number']
      end

      if attributes.key?(:'un_location_code')
        self.un_location_code = attributes[:'un_location_code']
      end

      if attributes.key?(:'facility_code')
        self.facility_code = attributes[:'facility_code']
      end

      if attributes.key?(:'facility_code_list_provider')
        self.facility_code_list_provider = attributes[:'facility_code_list_provider']
      end

      if attributes.key?(:'facility_type_code')
        self.facility_type_code = attributes[:'facility_type_code']
      end

      if attributes.key?(:'other_facility')
        self.other_facility = attributes[:'other_facility']
      end

      if attributes.key?(:'mode_of_transport')
        self.mode_of_transport = attributes[:'mode_of_transport']
      else
        self.mode_of_transport = nil
      end

      if attributes.key?(:'vessel')
        self.vessel = attributes[:'vessel']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @transport_call_id.nil?
        invalid_properties.push('invalid value for "transport_call_id", transport_call_id cannot be nil.')
      end

      if @mode_of_transport.nil?
        invalid_properties.push('invalid value for "mode_of_transport", mode_of_transport cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @transport_call_id.nil?
      return false if @mode_of_transport.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          transport_call_id == o.transport_call_id &&
          carrier_service_code == o.carrier_service_code &&
          export_voyage_number == o.export_voyage_number &&
          import_voyage_number == o.import_voyage_number &&
          un_location_code == o.un_location_code &&
          facility_code == o.facility_code &&
          facility_code_list_provider == o.facility_code_list_provider &&
          facility_type_code == o.facility_type_code &&
          other_facility == o.other_facility &&
          mode_of_transport == o.mode_of_transport &&
          vessel == o.vessel
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [transport_call_id, carrier_service_code, export_voyage_number, import_voyage_number, un_location_code, facility_code, facility_code_list_provider, facility_type_code, other_facility, mode_of_transport, vessel].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = MSCClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
